### ISSUE TITLE
Load webservices configuration through csv file 

### ISSUE THREAD

**Issue by jeperrot** [soprasteria/soapower#6]
Hi,
It's not anymore possible to load webservices configuration through a csv file. 
It's possible to get this feature back ?

Thanks.
Jep

**Comment by matcornic** [comment]
For information, this functionnality was available in 1.1.0 version, and an csv example file was available here : https://github.com/soapower/soapower/blob/1.1.0/app/controllers/Admin.scala

**Comment by matcornic** [comment]
@jeperrot Actually, there is a feature for webservices auto creation configuration, through "autorest" and "autosoap". See documentation :  http://soapower.readthedocs.io/en/2.1.x/usage.html?highlight=autorest#send-a-request-on-a-service-not-configured

You just have to use this form of endpoint in your real application (for SOAP)
`http://<soapowerurl>/autosoap/<newGroup>/<newEnvironment>/<backendEndPointURL>`

Exemple : `http://localhost:9010/autosoap/myNewGroup/myNewEnvironment/http://localhost:8080/myWebservice`
